jobs:
  run-script:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.4
    - name: Run script
      run: 'chmod +x get_ploblem_data.rb

        ruby get_ploblem_data.rb

        '
    - name: Update problem.json
      run: 'git config user.name "${GITHUB_ACTOR}"

        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

        git add problem.json db/csv_data/problem.csv

        git commit -m "Update problem.json"

        git push

        '
name: Update Problem
'on':
- workflow_dispatch
permissions: write-all
